# Generated by Django 5.1.6 on 2025-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_form_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_email',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='form_email',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='emp_documents/'),
        ),
        migrations.AddField(
            model_name='form_email',
            name='subject',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='form_email',
            name='t_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
