# Generated by Django 5.1.6 on 2025-03-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_form_email_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_email',
            old_name='pdf',
            new_name='pdfs',
        ),
    ]
