# Generated by Django 5.1.6 on 2025-04-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_pdf_form_email_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_email',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
